export const NavLinks = [
    { href: '/', key: 'home', label: 'Home' },
    { href: '/eb', key: 'eb', label: 'EB' },
    { href: '/departments', key: 'departments', label: 'Departements' },
    { href: '/calender', key: 'calnder', label: 'Calender' },
    { href: '/testimonials', key: 'testimonials', label: 'Testimonials' },
    { href: '/trackers', key: 'trackers', label: 'Trackers' },
]

export const Partner = [
    { key: 'Université de Tunis - El Manar', image: "/partners/campus.png", label: 'Université de Tunis - El Manar' },
    { key: 'Université Centrale', image: "/partners/centrale.gif", label: 'Université Centrale' },
    { key: 'TekUp', image: "/partners/tekup.gif", label: 'TekUp' },
    { key: 'Sesam', image: "/partners/sesam.png", label: 'Sesam' },
    { key: 'ULT', image: "/partners/ult.png", label: 'ULT' },
    { key: 'ESGITECH', image: "/partners/esgitech.gif", label: 'ESGTECH' },
    { key: 'Ted University', image: "/partners/ted.png", label: 'Ted University' },
    { key: 'ITeam', image: "/partners/iteam.gif", label: 'ITeam' },
]

export const Values = [
    { id: 1, image: "/icons/first.png", title: "Grit", desc: "We keep pushing forward and don't give up, even when things get tough or we face big challenges." },
    { id: 2, image: "/icons/two.png", title: "Work Hard, Play Harder, Work Even Harder", desc: 'We have fun but stay focused on what we need to do.' },
    { id: 3, image: "/icons/three.png", title: "Wise LC", desc: 'We make smart choices because we’ve learned from the past.' },
    { id: 4, image: "/icons/four.png", title: "value1", desc: 'fklhjdsklh fdslfkj dslfkj sldkfhj sdlkkf jhslkf hjsdl khfjs slfhj sd' },
]

export const Eb = [
    { id: 1, image: "/eb/benkhoudedited.gif", name: "Yassine Ben Khoud", position: 'LCVP OGT', email: 'yassine.benkhoud@aiesec.net' },
    { id: 2, image: "/eb/chojraedited.gif", name: "Aya Garbouj", position: 'LCVP OGV', email: 'aya.garbouj@aiesec.net' },
    { id: 3, image: "/eb/houssemedited.gif", name: "Houssem Bejaoui", position: 'LCVP IGV', email: 'houssembejaoui16@gmail.com ' },
    { id: 4, image: "/eb/wadiiedited.gif", name: "Wadi Gharbi", position: 'LCVP IGT', email: 'wadii.gharbi@aiesec.net ' },
    { id: 5, image: "/eb/mohaedited.gif", name: "Mohamed Ben Taleb", position: 'LCVP IM', email: 'mohamed.ben.taleb@aiesec.net' },
    { id: 6, image: "/eb/arijedited.gif", name: "Arij Zidi", position: 'LCVP TM', email: 'arij.zidi@aiesec.net' },
    { id: 7, image: "/eb/azeredited.gif", name: "Mohamed Azer Kouki", position: 'LCVP F&L', email: 'medazer.kouki@aiesec.net' },
    { id: 8, image: "/eb/islemedited.gif", name: "Islem Raissi", position: 'LCVP MKT', email: 'islem.raissi@aiesec.net' },
    { id: 9, image: "/eb/moslemedited.gif", name: "Moslem Ben Azzouz", position: 'LCVP BD', email: 'moslem.benazzouz@aiesec.net' },
]

export const departments = [
    { id: "ogv", title: 'Outgoing Global Volunteer', instalink: "https://www.instagram.com/ogv.university/", desc: 'We are responsible for sending people from our Campus to volunteering programs in different countries with our AIESEC Partners.', image: '/departments/ogv.gif' },
    { id: "ogt", title: 'Outgoing Global Ta/Te', instalink: "https://www.instagram.com/ogt.university/", desc: 'We send people from our Campus to professional Teaching or Talent internships in different countries with our AIESEC Partners.', image: '/departments/ogt.gif' },
    { id: "igv", title: 'Incoming Global Volunteer', instalink: "https://www.instagram.com/igv.cuba/", desc: 'We are responsible for bringing people from different countries to Tunisia to live our multiple volunteering projects.', image: '/departments/igv.gif' },
    { id: "igt", title: 'Incoming Global Ta/Te', instalink: "https://www.instagram.com/7arb_elpanique/", desc: 'We are responsible for bringing people from different countries to work in one of our professional Talent or Teaching opportunities.', image: '/departments/igt.gif' },
    { id: "im", title: 'Information Management', instalink: "https://www.instagram.com/im.university.24/", desc: 'We are responsible for data management, manipulation, and storage for each department and the LC overall.', image: '/departments/im.gif' },
    { id: "f&l", title: 'Finance And Legalities', instalink: "/", desc: 'We are one of the back-office departments, responsible for maintaining the healthy execution of the budget and controlling the compendium of the LC.', image: '/hero.gif' },
    { id: "tm", title: 'Talent Management', instalink: "/", desc: 'We are responsible for delivering a good experience for our membership.', image: '/hero.gif' },
    { id: "bd", title: 'Business Development & EwA', instalink: "/", desc: "We are responsible for enhancing our sales processes, driving business development, and maintaining the LC's professional brand in the professional network.", image: '/hero.gif' },
    { id: "mkt", title: 'Marketing', instalink: "/", desc: 'We are responsible for bringing new interested customers ready to go on exchange experiences with AIESEC.', image: '/departments/mkt.gif' },

]

export const footerLinks = [
    {
        id: 1,
        title: 'Departments',
        contents: [
            { name: 'Outgoing Global Volunteer', link: '/departments#ogv' },
            { name: 'Outgoing Global Ta/Te', link: '/departments#ogt' },
            { name: 'Incoming Global Volunteer', link: '/departments#igv' },
            { name: 'Incoming Global Ta/Te', link: '/departments#igt' },
            { name: 'Finance And Legalities', link: '/departments#f&l' },
            { name: 'Talent Management', link: '/departments#tm' },
            { name: 'Information Management', link: '/departments#im' },
            { name: 'Business Development', link: '/departments#bd' },
            { name: 'Marketing', link: '/departments#mkt' },
        ]
    },
    {
        id: 2,
        title: 'Testimonials',
        contents: [
            { name: "Alumni's Testimonials", link: '/testimonials#alumnitestimonials' },
            { name: 'EPs Tesimonials', link: '/testimonials#epstestimonials' },
            { name: 'Memories', link: '/testimonials#memories' },
        ]
    },
    {
        id: 3,
        title: 'Trackers',
        contents: [
            { name: 'University Dashboard', link: '/' },
        ]
    }
]

export const trackers = [
    {id:1, title:"university dashboard", desc:"fkjs dfldk jlk jsdlk jsdf ls", image:"/hero.gif", link:""},
    {id:1, title:"university dashboard", desc:"fkjs dfldk jlk jsdlk jsdf ls", image:"/hero.gif", link:""},
    {id:1, title:"university dashboard", desc:"fkjs dfldk jlk jsdlk jsdf ls", image:"/hero.gif", link:""},
    {id:1, title:"university dashboard", desc:"fkjs dfldk jlk jsdlk jsdf ls", image:"/hero.gif", link:""},
    {id:1, title:"university dashboard", desc:"fkjs dfldk jlk jsdlk jsdf ls", image:"/hero.gif", link:""},

]

export const images = [
    "/testimonials/paralexscroll/78.gif",
    "/testimonials/paralexscroll/42.gif",
    "/testimonials/paralexscroll/3.gif",
    "/testimonials/paralexscroll/88.gif",
    "/testimonials/paralexscroll/54.gif",
    "/testimonials/paralexscroll/20.gif",
    "/testimonials/paralexscroll/90.gif",
    "/testimonials/paralexscroll/101.gif",
    "/testimonials/paralexscroll/63.gif",
    "/testimonials/paralexscroll/1.gif",
    "/testimonials/paralexscroll/49.gif",
    "/testimonials/paralexscroll/70.gif",
    "/testimonials/paralexscroll/10.gif",
    "/testimonials/paralexscroll/93.gif",
    "/testimonials/paralexscroll/32.gif",
    "/testimonials/paralexscroll/55.gif",
    "/testimonials/paralexscroll/109.gif",
    "/testimonials/paralexscroll/18.gif",
    "/testimonials/paralexscroll/80.gif",
    "/testimonials/paralexscroll/46.gif",
    "/testimonials/paralexscroll/35.gif",
    "/testimonials/paralexscroll/100.gif",
    "/testimonials/paralexscroll/7.gif",
    "/testimonials/paralexscroll/108.gif",
    "/testimonials/paralexscroll/2.gif",
    "/testimonials/paralexscroll/64.gif",
    "/testimonials/paralexscroll/17.gif",
    "/testimonials/paralexscroll/5.gif",
    "/testimonials/paralexscroll/75.gif",
    "/testimonials/paralexscroll/26.gif",
    "/testimonials/paralexscroll/68.gif",
    "/testimonials/paralexscroll/50.gif",
    "/testimonials/paralexscroll/99.gif",
    "/testimonials/paralexscroll/74.gif",
    "/testimonials/paralexscroll/19.gif",
    "/testimonials/paralexscroll/106.gif",
    "/testimonials/paralexscroll/12.gif",
    "/testimonials/paralexscroll/31.gif",
    "/testimonials/paralexscroll/111.gif",
    "/testimonials/paralexscroll/9.gif",
    "/testimonials/paralexscroll/95.gif",
    "/testimonials/paralexscroll/85.gif",
    "/testimonials/paralexscroll/22.gif",
    "/testimonials/paralexscroll/13.gif",
    "/testimonials/paralexscroll/60.gif",
    "/testimonials/paralexscroll/8.gif",
    "/testimonials/paralexscroll/92.gif",
    "/testimonials/paralexscroll/6.gif",
    "/testimonials/paralexscroll/41.gif",
    "/testimonials/paralexscroll/30.gif",
    "/testimonials/paralexscroll/67.gif",
    "/testimonials/paralexscroll/33.gif",
    "/testimonials/paralexscroll/45.gif",
    "/testimonials/paralexscroll/76.gif",
    "/testimonials/paralexscroll/11.gif",
    "/testimonials/paralexscroll/47.gif",
    "/testimonials/paralexscroll/24.gif",
    "/testimonials/paralexscroll/53.gif",
    "/testimonials/paralexscroll/82.gif",
    "/testimonials/paralexscroll/48.gif",
    "/testimonials/paralexscroll/103.gif",
    "/testimonials/paralexscroll/81.gif",
    "/testimonials/paralexscroll/66.gif",
    "/testimonials/paralexscroll/71.gif",
    "/testimonials/paralexscroll/110.gif",
    "/testimonials/paralexscroll/38.gif",
    "/testimonials/paralexscroll/57.gif",
    "/testimonials/paralexscroll/72.gif",
    "/testimonials/paralexscroll/16.gif",
    "/testimonials/paralexscroll/4.gif",
    "/testimonials/paralexscroll/36.gif",
    "/testimonials/paralexscroll/87.gif",
    "/testimonials/paralexscroll/29.gif",
    "/testimonials/paralexscroll/27.gif",
    "/testimonials/paralexscroll/34.gif",
    "/testimonials/paralexscroll/96.gif",
    "/testimonials/paralexscroll/21.gif",
    "/testimonials/paralexscroll/59.gif",
    "/testimonials/paralexscroll/25.gif",
    "/testimonials/paralexscroll/56.gif",
    "/testimonials/paralexscroll/65.gif",
    "/testimonials/paralexscroll/61.gif",
    "/testimonials/paralexscroll/102.gif",
    "/testimonials/paralexscroll/28.gif",
    "/testimonials/paralexscroll/91.gif",
    "/testimonials/paralexscroll/15.gif",
    "/testimonials/paralexscroll/98.gif",
    "/testimonials/paralexscroll/62.gif",
    "/testimonials/paralexscroll/73.gif",
    "/testimonials/paralexscroll/104.gif",
    "/testimonials/paralexscroll/84.gif",
    "/testimonials/paralexscroll/43.gif",
    "/testimonials/paralexscroll/97.gif",
    "/testimonials/paralexscroll/39.gif",
    "/testimonials/paralexscroll/69.gif",
    "/testimonials/paralexscroll/94.gif",
    "/testimonials/paralexscroll/58.gif",
    "/testimonials/paralexscroll/105.gif",
    "/testimonials/paralexscroll/44.gif",
    "/testimonials/paralexscroll/51.gif",
    "/testimonials/paralexscroll/14.gif",
    "/testimonials/paralexscroll/40.gif",
    "/testimonials/paralexscroll/52.gif",
    "/testimonials/paralexscroll/83.gif",
    "/testimonials/paralexscroll/79.gif",
    "/testimonials/paralexscroll/77.gif",
    "/testimonials/paralexscroll/89.gif",
    "/testimonials/paralexscroll/86.gif",
    "/testimonials/paralexscroll/23.gif",
    "/testimonials/paralexscroll/37.gif",

];


export const routinesCards = [
    {
        title: "ulds",
        para1: " kfjndsk fljdnslfk dsnlfkjn dslfjkd ",
        image1: "/hero.gif",
        semititle: "hello lfdksjf l",
        image2: "/hero.gif",
    },
    {
        title: "ulds",
        para1: " kfjndsk fljdnslfk dsnlfkjn dslfjkd ",
        image1: "/hero.gif",
        semititle: "hello lfdksjf l",
        image2: "/hero.gif",
    },
    {
        title: "ulds",
        para1: " kfjndsk fljdnslfk dsnlfkjn dslfjkd ",
        image1: "/hero.gif",
        semititle: "hello lfdksjf l",
        image2: "/hero.gif",
    },
    {
        title: "ulds",
        para1: " kfjndsk fljdnslfk dsnlfkjn dslfjkd ",
        image1: "/hero.gif",
        semititle: "hello lfdksjf l",
        image2: "/hero.gif",
    },
]